-- Phase 1: authorize study-room Realtime and make shared room events durable.

-- Realtime Authorization evaluates these policies when a client subscribes
-- to or writes to a private `room:<uuid>` channel. Compare room ids as text so
-- malformed topics are rejected instead of raising a UUID cast exception.
DROP POLICY IF EXISTS "Study room members can receive realtime" ON realtime.messages;
CREATE POLICY "Study room members can receive realtime"
  ON realtime.messages
  FOR SELECT TO authenticated
  USING (
    extension IN ('broadcast', 'presence')
    AND split_part(realtime.topic(), ':', 1) = 'room'
    AND EXISTS (
      SELECT 1
        FROM public.room_members rm
       WHERE rm.room_id::text = split_part(realtime.topic(), ':', 2)
         AND rm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Study room members can send realtime" ON realtime.messages;
CREATE POLICY "Study room members can send realtime"
  ON realtime.messages
  FOR INSERT TO authenticated
  WITH CHECK (
    extension IN ('broadcast', 'presence')
    AND split_part(realtime.topic(), ':', 1) = 'room'
    AND EXISTS (
      SELECT 1
        FROM public.room_members rm
       WHERE rm.room_id::text = split_part(realtime.topic(), ':', 2)
         AND rm.user_id = auth.uid()
    )
  );

-- Document-change notifications were previously unauthenticated client
-- broadcasts. Store them as member-owned rows so receivers can trust the
-- database author and filename instead of an arbitrary websocket payload.
CREATE TABLE IF NOT EXISTS public.room_document_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id     uuid NOT NULL REFERENCES public.study_rooms(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  file_name   text NOT NULL CHECK (char_length(file_name) BETWEEN 1 AND 255),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS room_document_events_room_created_idx
  ON public.room_document_events (room_id, created_at DESC);

ALTER TABLE public.room_document_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS room_document_events_select ON public.room_document_events;
CREATE POLICY room_document_events_select
  ON public.room_document_events
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.room_members rm
       WHERE rm.room_id = room_document_events.room_id
         AND rm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS room_document_events_insert ON public.room_document_events;
CREATE POLICY room_document_events_insert
  ON public.room_document_events
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.room_members rm
       WHERE rm.room_id = room_document_events.room_id
         AND rm.user_id = auth.uid()
    )
  );

REVOKE ALL ON TABLE public.room_document_events FROM anon;
GRANT SELECT, INSERT ON TABLE public.room_document_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.room_document_events_id_seq TO authenticated;

-- Postgres Changes is the authoritative delivery path for shared mutations.
DO $$
DECLARE
  v_table text;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'room_strokes',
    'study_rooms',
    'room_members',
    'room_voice_notes',
    'room_blank_pages',
    'room_document_events'
  ]
  LOOP
    IF NOT EXISTS (
      SELECT 1
        FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime'
         AND schemaname = 'public'
         AND tablename = v_table
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', v_table);
    END IF;
  END LOOP;
END;
$$;

